### ISSUE TITLE
Feature Request: Log Improvements

### ISSUE THREAD

**Issue by cspalding** [featurehub-io/featurehub#1018]
**Is your feature request related to a problem? Please describe.**

As an engineer who self-hosts FeatureHub, I want to be able to debug issues using logs as well as metrics when I see issues come up with my FeatureHub installation (e.g. elevated 4xx/5xx response rates from certain components of the system). In FeatureHub's current state, I frequently see error logs that only contain an error message like `Failed jersey request` or `no data for valid api key <api-key>` without providing any details about the request/response content. Additional information about request failures in the logs shouldn't require turning on trace-level logs, which frequently provides too much information and increases my logging costs substantially.

**Describe the solution you'd like**

I'd love some more information when errors occur in my FeatureHub installation:
1. Request and response content
2. More information about request failures like the host that the request came from, and ideally some clearer messaging about the error.
3. Add request ids that are persisted for a request that moves across the FeatureHub components so that tracking an individual request is easier

I'm sure there are other ways to improve the logs that aren't coming to mind right now, but the issues above are what seem initially like they'll mitigate some of our confusion over where errors are originating in our FeatureHub installation.

**Describe alternatives you've considered**

1. Turning on trace-level logging. This is not an ideal solution because trace-level logs emit too much information and massively increase my logging cost.

**Additional context**

**Comment by gmartin-flexe** [comment]
I think in addition to what @cspalding requested, having consistent request ids across different components would really help to track down how they are interacting (or not).

**Comment by rvowles** [comment]
Heya - so a few things I can think of for these points.

1) Once the jersey tracing is turned on, the entire request and response content (all headers and body both received and sent) is actually put directly into the logs. Only the auth token is obfuscated. I presume the issue is that you don't want the req/response for successful requests only failed ones? This is quite difficult as we don't cache the full body of the incoming request waiting for the outgoing response, as that can be potentially dangerous in terms of denial of service. The other option is OpenTelemetry? Any suggestions that would make it easier are welcome here!

2) Clearer understanding of the error is probably best on a case by case basis, could you perhaps list some of the errors you are seeing so we can address those? We already have another ticket for addressing the errors in OAuth2 that people are seeing but any input from your team as to the errors would be helpful in making the logging more useful to people!

3) We use OpenTelemetry and wrap everything in OpenTelemetry support, so "request ids" (i.e. traceids) are already being used across the entire ecosystem. We don't surface OpenTracing trace contexts in the logs however, nor any extra W3C Baggage.  You don't normally put these in your logs because they represent spans, and so there is no consistent way to track them by just looking at logs alone. We could add a request id to the baggage and endeavour to log baggage would that be of use?

**Comment by rvowles** [comment]
I have added in support for fields from the OTEL baggage into the logs for this to allow cross thread tracking and delivery across the different services. I will be adding it to the UI as well as part of the next update. As I'm not getting more explicit feedback I will leave it at that and close the ticket once those are in.

**Comment by rvowles** [comment]
I'll be closing this out on  the next release with this piece of doc added: https://github.com/featurehub-io/featurehub/commit/fad1c0453c4adfae9b7d07ba0133bd72a4c25fc7
