### ISSUE TITLE
New Docker Image with latest version

### ISSUE THREAD

**Issue by Vaphen** [featurehub-io/featurehub#267]
**Docker images are currently only available for version 1.0.0 which doesn't include rollout strategies**
Currently, the latest version 1.0.0 of all featurehub docker images (party and standalone mr, edge, dacha, ...) is 3 months old and doesn't include the rollout strategy feature which is present in the demo (https://demo.featurehub.io/).

**Publish new docker images with the latest version**
It would be great if you could publish new docker images with the current version of featurehub. Currently, the documentation states a rollout strategy feature that can only be used if you build the application yourself.

**Creating a custom image is not an option for production use**
If you want to use a feature hub in production, it is very time consuming building the application and images on the own machine. This is not an option for real-world use cases in which a user only wants to pull the current image and get started directly.

**Comment by IrinaSouth** [comment]
Hi Vaphen, 

We are in the process of preparing the next dockerised version which we are aiming to release in the next couple days. It will include the full support for rollout strategies including percentage and attributes-based. Please stay tuned. We are tracking it here, once this issue is closed it should be all good to go https://github.com/featurehub-io/featurehub/issues/263

Thank you!

**Comment by Vaphen** [comment]
Hi Irina,

thank you for your fast response. I have not seen the release tasks.

Looking forward to the new release!

**Comment by IrinaSouth** [comment]
Hi Vaphen. This is now done and the new release can be installed with Docker. (v 1.1.1)
