### ISSUE TITLE
[Feature Request] Hierarchical toggle management

### ISSUE THREAD

**Issue by nosider** [featurehub-io/featurehub#900]
### Is your feature request related to a problem? Please describe.

**Feature toggles** (usually boolean ones) are an excellent way to decouple feature deployment from feature release. These are usually short-lived toggles that enable quick release cadence. Feature Hub is excellent at working with these toggles.

Some applications, though, also require that the available functionality is tailored to users based on various criteria. That criteria could be something like geo-location, arbitrary user attributes and other metadata. Traditionally such customisation was delegated to business logic in the application itself and at times driven through roles and user-level permissions, thus making them **Business Toggles** (I shall refer to them as such from here on).

Such approaches usually create high overhead to variation of the criteria such as:
 - Requiring code changes 
 - and/or configuration changes 
 - and/or data changes in databases

The above points, after some time, are offset through creation of custom-built UIs. These usually end up clunky and brittle, requiring significant investment over time to maintain and keep up with application development. This process is rather common across a multitude of organisation, meaning repeated and wasted effort across the industry. 

Yet, even after all that, those custom-built **Business Toggles** end up being rather simple key-value pairs that are constrained by various arbitrary conditions which are defined by the application. They have significant overlap in their functionality with the simple **Feature Toggles**.

The functionality in FeatureHub for toggles already covers most of what's desired of **Business Toggles**, with string and even whole `json` values that can be specified. The piece that is missing at the moment, and I am suggesting is implemented, is **hierarchy** in the defined features. 

Let's take a simple scenario: 
A company has an application. It has users that have the following arbitrary flags: 
 - `Customer Group`
 - `Customer`
 - `User Group`
 - `User Id`
 
From a management point of view, most of the feature permutations in the application would be coarse-grained. The vast majority of users are expected to have a consistent application experience based on a certain set of **Business Toggles** specified, for example, at `Customer Group` level. 
In some cases (exception rather than the rule) a specific `Customer` may desire their application experience to be adjusted with extra features turned on and some turned off. 
In rare cases features may need to be adjusted further by `User Group` and in extreme scenarios even by specific `User`.
With the current feature resolution flow (first-come-first-serve) and all features being in a single grid for the application, it will become very messy to maintain at scale.

### Describe the solution you'd like
The existing features available in FeatureHub can actually support the **Business Toggle** functionality from a technical standpoint with the current design. The challenge is to be able to present the toggles in a simple enough way so people (i.e. me with a poor old human brain) are able to consume and manage the toggles in an efficient way

I propose adding a new menu option, between `Features` and `API Keys` in the existing UI, called something like `Feature Groups`. The page shown in that "tab" would contain something like a hierarchical accordion, where user is able to specify rules (similar to how they can now under `Features` tab). The user is not able to add and remove the toggles themselves in the view, but rather be able to create logical rule groups for the toggles defined under the `Features` tab. 
Basically, the current `Features` tab allows a `rule` to be set per `feature`, while `Feature Groups` will allow `feature` to be set per `rule`.

Such structure would then permit logical groupings of feature states for common rules.

The accordion in the UI would specify one or more rules at its header, while the body can contain two collapsible sections.
**Section 1:** A subset list (zero or more items) of toggles from the `Features` tab, in the same structure, but with their own values. 
**Section 2:** A list of child accordions that allow nesting of rules.

A nested rule takes all the parent hierarchy rules, and adds their own to be more selective. Rule evaluation would thus have to start from "bottom-up", whereas the most-nested child rules are evaluated first, followed by their less selective parent rules and so on. If no rules are from the `Feature Groups` are matched, then the global values from `Features` tab are taken. 
Given the current evaluation of toggles is linear (AFAIK), the hierarchical structure can be flattened in the back-end, with rules ordered by specificity in descending order. 

### Describe alternatives you've considered
Launch Darkly supports relationships between toggles, where one toggle can have another toggle as part of the rule. This can be used to achieve a kind-of hierarchy-lite structure of toggles. Such an approach can be viable when toggle hierarchy complexity is low (which in most cases it would be), but requires good grasp of the structure by those managing the toggles, as things can get confusing quickly.

**Comment by rvowles** [comment]
Hey there! @IrinaSouth and I had a long chat about this, but you have raised some extra points, I'll see if I can summarise:

- typically you would achieve much of this with multiple applications, each application representing your group of features. The SDK is capable of watching multiple applications at once and amalgamating their features. This can in turn however lead it an overhead if you have to then replicate environments (say in a SaaS situation where you have different tenants represented as environments) and you have to replicate them everywhere.
- we discussed the concept of feature groups primarily as a means of categorisation (a feature belongs to a group) and a permission system (the existing groups can indicate which feature groups you are allowed to interact with - your permissions stay the same across the board however)
- surfacing those feature groups as a filter into the dashboard, especially given the significant reworking that Irina has done around the dashboard seems like a good idea, we hadn't thought of that, but we'll put it in the proposal
- FeatureHub has had what are called "shared rules" which exist at the Application level since version 1.4, but they have been API only because of the complexity of the current dashboard. The idea is that you define a rule and then you can just apply it to a feature value anywhere you like, but you need to specify what value it will be. This allows the same rule to be applied to many different types of feature values (bool, json, string, number) but still be "local". This is likely what we will be rolling out over the next few months.
- We agreed early on we wouldn't support chaining feature values together because of exactly the reason you mentioned, very complicated very quickly :-)

I very much appreciate your very detailed thoughts and exposition!

**Comment by nosider** [comment]
Thanks @rvowles and @IrinaSouth

Yeah, I thought about using "Applications" as a way to simulate hierarchy, and it works, but only in cases where there is only one level of hierarchy to apply. It does, though, result is some major caveats even when there is just a single level: 
 - splitting by "application" means that if, say, a new toggle needs to be added, it needs to be done for every "application" - resulting in redundant manual steps multiplied by the number of "applications". Say, for example, the top-level hierarchy is pricing-tier. The toggles for each tier will need to be independently maintained without any inherent "safety" that all toggles are set up consistently between the "applications" 
 - the decision which "application" is being used is now the responsibility of the business-logic in the software, which tightly couples the "toggle hierarchy workaround" into the implementation detail, essentially resulting in "leaking" of the workaround into the software, moving us back towards where we are trying to escape from. 

From purely technical point of view, the desired functionality is actually already possible, but would mean that there's an explosion of rules to evaluate and the maintenance of those rules will become insurmountable, which is why I am suggesting is a UI centric approach which just simplifies the presentation and maintenance of the hierarchy while the basic underlying logic of FeatureHub remains the same. 

The "Shared Rules" thing is pretty cool, but since its not surfaced by the UI it will not be possible for support teams to manage them. It also means that the issue of "rule-per-toggle" structure, instead of the "toggle-override-per-rule", remains and makes long term logical hierarchy management infeasible.

**Comment by rvowles** [comment]
More questions sorry :-) 

- if an application is a pricing tier, would that matter so much, if every service in your product for example just uses all the toggles from all the applications? So instead of specifying a single API Key in your service, you specify - say 4? The SDKs are designed so the repository of feature toggles is separate from what is feeding them, so you can have your features appear in a single FH application, and yet still be usable in all of your services? 

I think the environment business is a killer here - if a customer for example is an environment (horizontal) then you would have to recreate that environment in every application and it seems an unnecessary complexity. Its something that we know people have done in the meantime however, but IMHO feature grouping with the permission system is a much better choice as it lets you keep all that in one application and have horizontal and vertical slicing of your features within the existing dashboard structure. 

And yes, without shared rules, life is going to get quite complex. Feature auditing and intelligent optimisitic locking comes in the next version, and we also have environment checkpointing/snapshotting on the cards as well, so the dashboard has some significant updates ahead!

**Comment by rvowles** [comment]
Hiya - I mean, you define F1 only in App1 and F2 only in App2. And your microservices (for example) will include features from both applications. You only need to change F1 in App1 as it would only exist in App1. 

App1 == a FeatureHub Application, App2 = a FeatureHub Application, both within the same portfolio controlled by the same groups and permissions and service accounts. You then get two API Keys - one for each application, and get your own service to use both keys.

**Comment by nosider** [comment]
Here is a simple user case:
Application `App1-Normal`, Flags `F1` == `false`, `F2` == `true`
Application `App1-Premium` Flags `F1` == `true`, `F3` == `true`

Software, would then request toggles, specifying the API keys for apps in a cumulative manner. So if the customer is:
 - `Normal` only the API key for `App1-Normal` would be specified, resulting in `F1` == `false` and `F2` == `true`
 - `Premium` both the API keys for `App1-Normal` and `App1-Premium` are specified resulting in `F1` == `true`, `F2` == `true`, `F3` == `true`

Is my understanding correct?

**Comment by nosider** [comment]
Ah, I see. That is what I failed to communicate :facepalm: 

No the customer does not need to manage the toggles. The customer, depending on their choices (sign up plan, extra features requested), will have differing metadata values assigned, and those will be provided to FH, which will then use them to drive the toggle decisions.

**Comment by rvowles** [comment]
Ah, if thats the case, that makes it a bit easier as the we can make the shared strategies manually attach to a feature value, or automatically attach based on environments. So if you set up strategies based on customer tenanting, you could use them on your production environments so every feature value for production would have strategies for each tenant allowing you to override F1 - shared strategies can be attached and disabled as well, so they can be set up, but not be in active use - thats important as shared strategies when applied must have a value associated with them, and the default for boolean is false for example. It would allow you to have a baseline set of flags or values, and only override them for specific tenants when their are different but they would always be there in front of you to do so.

The extra functionality we need to add to the backend is the ability to auto-provision strategies based on environments which would make them more usable, and of course all the front end work to make this visible :-) It might be interesting to be able to associate groups with those shared strategies as well, because then you actually could let customers see the dashboard and change their own toggles.

**Comment by rvowles** [comment]
You can attach as many strategies and shared strategies as you like at the moment, but a strategy once matched takes its value, its a ruleset style - it starts at the top and once it matches, it just returns the value you assigned.

**Comment by nosider** [comment]
Is there a way to create a deterministic sequence of evaluation of strategies? Do they have priority sequence?

**Comment by rvowles** [comment]
Heya - Yes, they are evaluated in the order they appear in the UI, shared strategies are always after feature value specific strategies however. So any strategies you add specifically to this feature value get evaluated first (in their listed ordere), and then the rest in the order in which they are attached. If none match then the default value is taken.

**Comment by nosider** [comment]
Thanks @rvowles 

I assume the UI respects the order as per the `rolloutStrategyInstances` in the `FeatureValue` provided to the `/mr-api/features/{eid}/feature/{key}` API calls, right? 
https://github.com/featurehub-io/featurehub/blob/b09b8557dcba24df84180bfc1241ed242082920c/infra/api-bucket/files/mrapi/1.1.8.yaml#L2055

***I do not see a way to re-order the strategies in the UI***

I guess in this approach, with each toggle customised using shared strategies will display potentially with a huge list of options to the user maintaining it, especially if a non-insignificant number of variation from standard is requires for that toggle. 
![image](https://user-images.githubusercontent.com/25810702/206972401-964ab928-3ecd-4904-9ab4-988535a2467d.png)

Is there a limit, enforced or sanity, for the number of strategies attached to a toggle?

**Comment by rvowles** [comment]
HI @nosider - except by the APi  there is currently no way in the UI to resolve ordering. There is a ticket for it #901 and its on our roadmap. And no, there is no limit on the number of strategies attached to a single feature value.

**Comment by axblueblader** [comment]
hi hi @rvowles, want to double check the 'order in which they appear' evaluation. From the example image, is it bottom up ('zxc' first) or top down ('qaz' first)?

**Comment by IrinaSouth** [comment]
just an update here, strategy reordering has been done now and released in 1.6.1 @nosider

**Comment by nosider** [comment]
Oh wow! Thank you @IrinaSouth and @rvowles! I will check it out 😁

**Comment by IrinaSouth** [comment]
This feature is now available in 1.7.0 release :)

**Comment by nosider** [comment]
Thank you so much @IrinaSouth and @rvowles! You are amazing!

**Comment by IrinaSouth** [comment]
Thanks @nosider  - this was a great idea, I really like this new addition :)  Should be quite useful for users building SaaS apps and managing customer's feature flags.
